pipeline {
  agent any

  

  stages {

    stage('Clone') {
      steps {
        git 'https://github.com/Manoj18121812/CICD-Student-Management.git'
      }
    }

    stage('Build') {
      steps {
        sh '''
        cd Student
        mvn clean package -DskipTests
        '''
      }
    }

    stage('Docker Build') {
      steps {
        sh '''
        cd Student
        docker build -t student-app .
        '''
      }
    }

    stage('Deploy') {
      steps {
        sh '''
        docker rm -f student || true
        docker run -d -p 8081:8080 --name student student-app
        '''
      }
    }

  }
}

